# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d3b80839a482d0c48b938df37623eb2b775d028f282ac5ce89635c08f2debf6292bcc0988f5f320f5466b136359ab16c9d77129db6f0bec84ac746707a600ef

test:
  secret_key_base: 7a27badece0397f43131df14f594b3f8ad2a003922601bdf930075bb5c4ac6e2271997b60e9d1b116b903bbadc65798537719d598489e99664b287e4269248e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
